apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather-aqi.fullname" . }}-weather
  labels:
    {{- include "weather-aqi.labels" . | nindent 4 }}
    app.kubernetes.io/component: weather
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.env.weatherService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "weather-aqi.selectorLabels" (merge (dict "component" "weather") .) | nindent 4 }}
